/* SBL biomechanics glossary — accessible, vanilla JS tooltips.
   Markup contract:
     <span class="gloss" data-term="mev">MEV</span>
   On DOMContentLoaded we:
     1) Read every .gloss element
     2) Inject role="tooltip" spans into the DOM (one per term, deduped)
     3) Wire tabindex, aria-describedby, and event listeners
     4) Position the tooltip absolutely on demand
   Plain-English definitions are deliberate translations of the industry's
   high-friction lexicon — the site's mission is to cut through that noise.
*/
(function () {
  'use strict';

  var GLOSSARY = {
    'progressive-overload':
      'Gradually increasing the weight, reps, or sets over time so the body is forced to adapt and grow. The single non-negotiable driver of muscle growth.',
    'proximity-to-failure':
      'How close a lifter pushes a set to the physical point where they could not complete another clean rep. Most growth happens within a few reps of failure.',
    'junk-volume':
      'Sets that consume your recovery capacity but are not hard enough — too far from failure or too poorly executed — to actually trigger new muscle growth.',
    'mev':
      'Minimum Effective Volume — the smallest number of hard sets per week that will measurably grow a muscle. Below this, you stagnate.',
    'mrv':
      'Maximum Recoverable Volume — the most weekly sets you can do before your body stops recovering and progress halts. Above this, you regress.',
    'lengthened-partials':
      'Performing only the half of an exercise where the target muscle is fully stretched, instead of the full range of motion. Emerging research suggests this drives extra hypertrophy in certain movements.',
    'resistance-profile':
      'How heavy or light an exercise feels at different points in its range, determined by leverage and the direction of gravity (or cable angle).',
    'energy-partitioning':
      'How the body decides whether to use the calories you eat to build new muscle tissue or store them as body fat. Training status and energy balance dominate this.',
    'failure':
      'Muscular failure: the rep where, with strict form, you physically cannot complete another. Different from "feeling tired" — it is the mechanical endpoint of a set.',
    'hypertrophy':
      'Muscle growth — the increase in size of muscle fibers in response to mechanical tension and adequate recovery. The goal of nearly all training on this site.',
    'mechanical-tension':
      'The primary stimulus for muscle growth: force generated by the muscle against a load, especially when the muscle is in a stretched position.',
    'mesocycle':
      'A block of training (typically 4–6 weeks) with a coherent goal — accumulating volume, peaking strength — that ends in a recovery week before the next block.',
    'deload':
      'A planned week of reduced training volume or intensity that dissipates accumulated fatigue so progress can resume in the next mesocycle.',
    'rom':
      'Range of Motion — how far you move the weight from the start to the end of a rep. Generally, full ROM beats partial ROM, with the lengthened position being the most productive portion.'
  };

  var activeTooltip = null;
  var hoverDelay = null;
  var HOVER_DELAY_MS = 300;

  function makeTooltipEl(term, definition) {
    var existing = document.getElementById('tt-' + term);
    if (existing) return existing;
    var tt = document.createElement('span');
    tt.id = 'tt-' + term;
    tt.className = 'tooltip';
    tt.setAttribute('role', 'tooltip');
    tt.hidden = true;
    tt.textContent = definition;
    document.body.appendChild(tt);
    return tt;
  }

  function position(trigger, tooltip) {
    // Compute trigger rect, then place tooltip above (or below if no room above).
    var tRect = trigger.getBoundingClientRect();
    // Measure tooltip after revealing it visually but before fading in.
    tooltip.hidden = false;
    var tipRect = tooltip.getBoundingClientRect();
    var vw = window.innerWidth;
    var vh = window.innerHeight;
    var gap = 8;

    var top = tRect.top - tipRect.height - gap;
    var placeBelow = top < 8;
    if (placeBelow) top = tRect.bottom + gap;

    var left = tRect.left + (tRect.width / 2) - (tipRect.width / 2);
    left = Math.max(8, Math.min(left, vw - tipRect.width - 8));

    // Vertical guard: if no room either way, pin to viewport top.
    if (top + tipRect.height > vh - 8) top = Math.max(8, vh - tipRect.height - 8);

    tooltip.style.left = left + 'px';
    tooltip.style.top = top + 'px';
  }

  function show(trigger) {
    var term = trigger.dataset.term;
    if (!term || !GLOSSARY[term]) return;
    var tooltip = makeTooltipEl(term, GLOSSARY[term]);
    if (activeTooltip && activeTooltip !== tooltip) hideActive();
    position(trigger, tooltip);
    // Re-flow for transition.
    requestAnimationFrame(function () {
      tooltip.classList.add('is-open');
    });
    activeTooltip = tooltip;
    trigger._sblTooltip = tooltip;
  }

  function hide(trigger) {
    var tooltip = trigger._sblTooltip;
    if (!tooltip) return;
    tooltip.classList.remove('is-open');
    // After the fade, hide attribute to prevent screen-reader announcement noise.
    window.setTimeout(function () {
      if (!tooltip.classList.contains('is-open')) tooltip.hidden = true;
    }, 180);
    if (activeTooltip === tooltip) activeTooltip = null;
  }

  function hideActive() {
    if (!activeTooltip) return;
    var tooltip = activeTooltip;
    tooltip.classList.remove('is-open');
    window.setTimeout(function () {
      if (!tooltip.classList.contains('is-open')) tooltip.hidden = true;
    }, 180);
    activeTooltip = null;
  }

  function wireTrigger(trigger) {
    var term = trigger.dataset.term;
    if (!term || !GLOSSARY[term]) return;

    // Ensure accessibility wiring.
    if (!trigger.hasAttribute('tabindex')) trigger.setAttribute('tabindex', '0');
    trigger.setAttribute('aria-describedby', 'tt-' + term);
    // Pre-create the tooltip element so screen readers can find it via aria-describedby.
    makeTooltipEl(term, GLOSSARY[term]);

    trigger.addEventListener('mouseenter', function () {
      window.clearTimeout(hoverDelay);
      hoverDelay = window.setTimeout(function () { show(trigger); }, HOVER_DELAY_MS);
    });
    trigger.addEventListener('mouseleave', function () {
      window.clearTimeout(hoverDelay);
      hide(trigger);
    });
    trigger.addEventListener('focus', function () {
      window.clearTimeout(hoverDelay);
      show(trigger);
    });
    trigger.addEventListener('blur', function () {
      window.clearTimeout(hoverDelay);
      hide(trigger);
    });
    trigger.addEventListener('click', function (e) {
      // Touch + click toggle, also stops the browser from scrolling when triggers are nested in links.
      e.preventDefault();
      if (trigger._sblTooltip && trigger._sblTooltip.classList.contains('is-open')) {
        hide(trigger);
      } else {
        show(trigger);
      }
    });
  }

  function init() {
    // Global keyboard dismissal.
    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape' && activeTooltip) hideActive();
    });
    // Outside-tap dismissal for touch users.
    document.addEventListener('touchstart', function (e) {
      if (!activeTooltip) return;
      var inGloss = e.target.closest && e.target.closest('.gloss');
      var inTip = e.target.closest && e.target.closest('.tooltip');
      if (!inGloss && !inTip) hideActive();
    }, { passive: true });
    // Reposition active tooltip on resize / scroll.
    window.addEventListener('scroll', function () {
      if (activeTooltip) hideActive();
    }, { passive: true });
    window.addEventListener('resize', function () {
      if (activeTooltip) hideActive();
    });

    var triggers = document.querySelectorAll('.gloss');
    triggers.forEach(wireTrigger);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
